# MongoDB Settings
db.uri=mongodb+srv://bingeitAdmin:bingeitAdminPass@bingeitcluster.f1qwsrk.mongodb.net/?retryWrites=true&w=majority&appName=bingeitCluster

db.name=bingeit

# Email Settings
mail.host=smtp.gmail.com
mail.port=587
mail.username=bingeit.noreply@gmail.com
mail.password=nimjlazrwnedfhwx
mail.auth=true
mail.starttls.enable=true