name: Keep Render Awake

on:
  schedule:
    # Every 10 minutes
    - cron: "*/10 * * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render
        run: |
          curl -L --fail https://bingeit-1o6o.onrender.com/login